language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install flake8 
# command to run tests
script:
    - flake8 .
    - nosetests
#integration with Slack
notifications:
  slack: nodcode:1vNMEjQnaHr57PaMxnYkj9lw
